version: '3.8'

services:
  portfolio:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      # Mount source code for development (comment out for production)
      # - .:/app
      # - /app/node_modules
      # - /app/.next
